# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:5
      - image: mysql:5.6
          environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Create MySQL Table
          command: mysql -u ubuntu -e "create database wordpress"