version: 2.0
jobs:
  build:
    working_directory: /var/www/html
    docker:
      - image: php:7.1-apache
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu
    steps:
      - checkout
      - run:
          name: MySQL TEST
          command: mysql -u ubuntu -e "create database wordpress"